# render.yaml - การตั้งค่า Render Service
services:
  - type: web
    name: n8n-vaccine-workflow
    env: docker
    dockerfilePath: ./Dockerfile
    plan: starter # หรือ standard, pro ตามความต้องการ
    region: singapore # เลือก region ที่ใกล้ที่สุด
    branch: main
    buildCommand: ""
    startCommand: "n8n start"
    
    # การตั้งค่า Environment Variables
    envVars:
      - key: NODE_ENV
        value: production
      
      - key: N8N_HOST
        value: 0.0.0.0
      
      - key: N8N_PORT
        value: 5678
      
      - key: N8N_PROTOCOL
        value: https
      
      - key: N8N_EDITOR_BASE_URL
        fromService:
          type: web
          name: n8n-vaccine-workflow
          property: host
      
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: n8n-vaccine-workflow
          property: host
      
      - key: N8N_ENCRYPTION_KEY
        generateValue: true # Render จะสร้างค่าสุ่มให้
      
      - key: DB_TYPE
        value: postgresdb
      
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-postgres
          property: host
      
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-postgres
          property: port
      
      - key: DB_POSTGRESDB_DATABASE
        fromDatabase:
          name: n8n-postgres
          property: database
      
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: n8n-postgres
          property: user
      
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-postgres
          property: password
      
      # LINE Bot Credentials (ตั้งค่าใน Render Dashboard)
      - key: LINE_CHANNEL_ACCESS_TOKEN
        sync: false # ป้อนเองใน Dashboard
      
      - key: LINE_CHANNEL_SECRET
        sync: false
      
      # Google API Credentials
      - key: GOOGLE_ACCESS_TOKEN
        sync: false
      
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      
      - key: GOOGLE_CLIENT_ID
        sync: false
      
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      
      - key: GOOGLE_SPREADSHEET_ID
        sync: false
      
      # OpenAI API Key (สำหรับ AI Router)
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: n8n-postgres
    databaseName: n8n_db
    user: n8n_user
    plan: starter # หรือตามความต้องการ
    region: singapore